### ISSUE TITLE
Failed to build

### ISSUE THREAD

**Issue by appstronautstudios** [smodin-io/fast-text-language-detection#4]
**npm i @smodin/fast-text-language-detection**

```
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\***\AppData\Roaming\nvm\v14.18.0\node_modules\npm\node_modules\node-gyp\lib\build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:282:12)
gyp ERR! System Windows_NT 10.0.19043
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\***\\AppData\\Roaming\\nvm\\v14.18.0\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\***\workspace\***\node_modules\fast-text
```

- node -v v14.18.0
- npm -v 6.14.15
- node-gyp -v v5.1.0
- python --version Python 3.10.2

[2022-10-21T21_23_58_100Z-debug.log](https://github.com/smodin-io/fast-text-language-detection/files/9842597/2022-10-21T21_23_58_100Z-debug.log)

**I tried some of the suggestions listed here without any luck**
https://stackoverflow.com/questions/45801457/node-js-python-not-found-exception-due-to-node-sass-and-node-gyp/53009640#53009640

I'm assuming this is a version mismatch or a missing requirement. Can your provide any additional info?

**Comment by Aivean** [comment]
Have the same issue (on github hosted runner):
https://github.com/spaceshelter/orbitar/actions/runs/3334951748/jobs/5518489591

```
runs-on: ubuntu-latest
node-version: "16"
"@smodin/fast-text-language-detection": "^0.2.3",
```

**Comment by KevinDanikowski** [comment]
On my macbook pro machine:
node -v v14.17.0
npm -v 6.14.13
python --version Python 3.8.10

and it's working without issue.

I recommend using the dockerfile mentioned in the README.md, this is what we're using currently with no issues.

**Comment by appstronautstudios** [comment]
The docker issue you linked in the README appears to pertain to the Python executable not being correctly configured. Neither my issue nor @Aivean present as Python failures.

I have included my full node-gyp rebuild log to hopefully add additional data to this issue:

```
C:\Users\*****\workspace\multidetect\node_modules\fast-text>if not defined npm_config_node_gyp (node "C:\Users\*****\AppData\Roaming\nvm\v14.18.0\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\*****\AppData\Roaming\nvm\v14.18.0\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "-m" switch.
  args.cc
  dictionary.cc
  fasttext.cc
  matrix.cc
  model.cc
  productquantizer.cc
C:\Users\*****\workspace\multidetect\node_modules\fast-text\lib\src\productquantizer.h(31,21): warning C4305: 'initializing': truncation from 'double' to 'const fasttext::real' (compiling source file ..\lib\src\productquantizer.cc) [C:\Users\*****\workspace\multidetect\node_modules\fast-text\build\fasttext.vcxproj]
C:\Users\*****\workspace\multidetect\node_modules\fast-text\lib\src\productquantizer.cc(133,73): error C2039: 'to_string': is not a member of 'std' [C:\Users\*****\workspace\multidetect\node_modules\fast-text\build\fasttext.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\include\numeric(23): message : see declaration of 'std' [C:\Users\*****\workspace\multidetect\node_modules\fast-text\build\fasttext.vcxproj]
C:\Users\*****\workspace\multidetect\node_modules\fast-text\lib\src\productquantizer.cc(133,82): error C3861: 'to_string': identifier not found [C:\Users\*****\workspace\multidetect\node_modules\fast-text\build\fasttext.vcxproj]
C:\Users\*****\workspace\multidetect\node_modules\fast-text\lib\src\productquantizer.cc(132,32): error C2512: 'std::invalid_argument': no appropriate default constructor available [C:\Users\*****\workspace\multidetect\node_modules\fast-text\build\fasttext.vcxproj]
C:\Users\*****\workspace\multidetect\node_modules\fast-text\lib\src\productquantizer.cc(133,99): message : No constructor could take the source type, or constructor overload resolution was ambiguous [C:\Users\*****\workspace\multidetect\node_modules\fast-text\build\fasttext.vcxproj]
C:\Users\*****\workspace\multidetect\node_modules\fast-text\lib\src\productquantizer.h(31,21): warning C4305: 'initializing': truncation from 'double' to 'const fasttext::real' (compiling source file ..\lib\src\model.cc) [C:\Users\*****\workspace\multidetect\node_modules\fast-text\build\fasttext.vcxproj]
C:\Users\*****\workspace\multidetect\node_modules\fast-text\lib\src\productquantizer.h(31,21): warning C4305: 'initializing': truncation from 'double' to 'const fasttext::real' (compiling source file ..\lib\src\fasttext.cc) [C:\Users\*****\workspace\multidetect\node_modules\fast-text\build\fasttext.vcxproj]
C:\Users\*****\workspace\multidetect\node_modules\fast-text\lib\src\fasttext.cc(290,40): warning C4018: '<': signed/unsigned mismatch [C:\Users\*****\workspace\multidetect\node_modules\fast-text\build\fasttext.vcxproj]
C:\Users\*****\workspace\multidetect\node_modules\fast-text\lib\src\fasttext.cc(615,24): warning C4018: '<': signed/unsigned mismatch [C:\Users\*****\workspace\multidetect\node_modules\fast-text\build\fasttext.vcxproj]
C:\Users\*****\workspace\multidetect\node_modules\fast-text\lib\src\fasttext.cc(620,26): warning C4018: '<': signed/unsigned mismatch [C:\Users\*****\workspace\multidetect\node_modules\fast-text\build\fasttext.vcxproj]
C:\Users\*****\workspace\multidetect\node_modules\fast-text\lib\src\fasttext.cc(630,24): warning C4018: '<': signed/unsigned mismatch [C:\Users\*****\workspace\multidetect\node_modules\fast-text\build\fasttext.vcxproj]
C:\Users\*****\workspace\multidetect\node_modules\fast-text\lib\src\fasttext.cc(633,26): warning C4018: '<': signed/unsigned mismatch [C:\Users\*****\workspace\multidetect\node_modules\fast-text\build\fasttext.vcxproj]
  qmatrix.cc
  utils.cc
  vector.cc
C:\Users\*****\workspace\multidetect\node_modules\fast-text\lib\src\productquantizer.h(31,21): warning C4305: 'initializing': truncation from 'double' to 'const fasttext::real' (compiling source file ..\lib\src\qmatrix.cc) [C:\Users\*****\workspace\multidetect\node_modules\fast-text\build\fasttext.vcxproj]
  nodeArgument.cc
C:\Users\*****\workspace\multidetect\node_modules\fast-text\lib\src\productquantizer.h(31,21): warning C4305: 'initializing': truncation from 'double' to 'const fasttext::real' (compiling source file ..\lib\src\vector.cc) [C:\Users\*****\workspace\multidetect\node_modules\fast-text\build\fasttext.vcxproj]
  classifierWorker.cc
  trainWorker.cc
  vectorWorker.cc
  nnWorker.cc
  wrapper.cc
C:\Users\*****\workspace\multidetect\node_modules\fast-text\lib\src\productquantizer.h(31,21): warning C4305: 'initializing': truncation from 'double' to 'const fasttext::real' (compiling source file ..\src\classifierWorker.cc) [C:\Users\*****\workspace\multidetect\node_modules\fast-text\build\fasttext.vcxproj]
C:\Users\*****\workspace\multidetect\node_modules\fast-text\lib\src\productquantizer.h(31,21): warning C4305: 'initializing': truncation from 'double' to 'const fasttext::real' (compiling source file ..\src\trainWorker.cc) [C:\Users\*****\workspace\multidetect\node_modules\fast-text\build\fasttext.vcxproj]
C:\Users\*****\workspace\multidetect\node_modules\fast-text\src\classifierWorker.cc(28,13): warning C4996: 'Nan::Callback::Call': was declared deprecated [C:\Users\*****\workspace\multidetect\node_modules\fast-text\build\fasttext.vcxproj]
C:\Users\*****\workspace\multidetect\node_modules\fast-text\src\classifierWorker.cc(60,13): warning C4996: 'Nan::Callback::Call': was declared deprecated [C:\Users\*****\workspace\multidetect\node_modules\fast-text\build\fasttext.vcxproj]
C:\Users\*****\workspace\multidetect\node_modules\fast-text\src\trainWorker.cc(15,7): warning C4286: 'const std::invalid_argument &': is caught by base class ('const stdext::exception &')
 on line 13 [C:\Users\*****\workspace\multidetect\node_modules\fast-text\build\fasttext.vcxproj]
C:\Users\*****\workspace\multidetect\node_modules\fast-text\src\trainWorker.cc(28,13): warning C4996: 'Nan::Callback::Call': was declared deprecated [C:\Users\*****\workspace\multidetect\node_modules\fast-text\build\fasttext.vcxproj]
C:\Users\*****\workspace\multidetect\node_modules\fast-text\src\trainWorker.cc(38,13): warning C4996: 'Nan::Callback::Call': was declared deprecated [C:\Users\*****\workspace\multidetect\node_modules\fast-text\build\fasttext.vcxproj]
C:\Users\*****\workspace\multidetect\node_modules\fast-text\lib\src\productquantizer.h(31,21): warning C4305: 'initializing': truncation from 'double' to 'const fasttext::real' (compiling source file ..\src\vectorWorker.cc) [C:\Users\*****\workspace\multidetect\node_modules\fast-text\build\fasttext.vcxproj]
C:\Users\*****\workspace\multidetect\node_modules\fast-text\lib\src\productquantizer.h(31,21): warning C4305: 'initializing': truncation from 'double' to 'const fasttext::real' (compiling source file ..\src\wrapper.cc) [C:\Users\*****\workspace\multidetect\node_modules\fast-text\build\fasttext.vcxproj]
C:\Users\*****\workspace\multidetect\node_modules\fast-text\src\vectorWorker.cc(17,7): warning C4286: 'const std::invalid_argument &': is caught by base class ('const stdext::exception &') on line 15 [C:\Users\*****\workspace\multidetect\node_modules\fast-text\build\fasttext.vcxproj]
C:\Users\*****\workspace\multidetect\node_modules\fast-text\src\vectorWorker.cc(31,13): warning C4996: 'Nan::Callback::Call': was declared deprecated [C:\Users\*****\workspace\multidetect\node_modules\fast-text\build\fasttext.vcxproj]
C:\Users\*****\workspace\multidetect\node_modules\fast-text\src\vectorWorker.cc(49,13): warning C4996: 'Nan::Callback::Call': was declared deprecated [C:\Users\*****\workspace\multidetect\node_modules\fast-text\build\fasttext.vcxproj]
C:\Users\*****\workspace\multidetect\node_modules\fast-text\src\wrapper.cc(199,24): warning C4018: '<': signed/unsigned mismatch [C:\Users\*****\workspace\multidetect\node_modules\fast-text\build\fasttext.vcxproj]
C:\Users\*****\workspace\multidetect\node_modules\fast-text\src\wrapper.cc(204,26): warning C4018: '<': signed/unsigned mismatch [C:\Users\*****\workspace\multidetect\node_modules\fast-text\build\fasttext.vcxproj]
C:\Users\*****\workspace\multidetect\node_modules\fast-text\src\wrapper.cc(214,24): warning C4018: '<': signed/unsigned mismatch [C:\Users\*****\workspace\multidetect\node_modules\fast-text\build\fasttext.vcxproj]
C:\Users\*****\workspace\multidetect\node_modules\fast-text\src\wrapper.cc(217,26): warning C4018: '<': signed/unsigned mismatch [C:\Users\*****\workspace\multidetect\node_modules\fast-text\build\fasttext.vcxproj]
  fasttext.cc
C:\Users\*****\workspace\multidetect\node_modules\fast-text\lib\src\productquantizer.h(31,21): warning C4305: 'initializing': truncation from 'double' to 'const fasttext::real' (compiling source file ..\src\nnWorker.cc) [C:\Users\*****\workspace\multidetect\node_modules\fast-text\build\fasttext.vcxproj]
  win_delay_load_hook.cc
C:\Users\*****\workspace\multidetect\node_modules\fast-text\src\nnWorker.cc(29,13): warning C4996: 'Nan::Callback::Call': was declared deprecated [C:\Users\*****\workspace\multidetect\node_modules\fast-text\build\fasttext.vcxproj]
C:\Users\*****\workspace\multidetect\node_modules\fast-text\src\nnWorker.cc(61,13): warning C4996: 'Nan::Callback::Call': was declared deprecated [C:\Users\*****\workspace\multidetect\node_modules\fast-text\build\fasttext.vcxproj]
C:\Users\*****\workspace\multidetect\node_modules\fast-text\lib\src\productquantizer.h(31,21): warning C4305: 'initializing': truncation from 'double' to 'const fasttext::real' (compiling source file ..\src\fasttext.cc) [C:\Users\*****\workspace\multidetect\node_modules\fast-text\build\fasttext.vcxproj]
```

I have also tried to create a fresh local project on an Ubuntu machine I have. On that machine:

`npm i @smodin/fast-text-language-detection`

Failed with a very similar stacktrace to the one @Aivean listed. Relevant info for that machine:

Ubuntu 20.04.5 LTS
node -v 18.12.1
node-gyp -v v9.1.0

Could there is a dependency you have installed locally that is required for this library to correctly install via npm?

**Comment by Aivean** [comment]
@appstronautstudios , I think my failure on `ubuntu-latest` could be caused by the missing python.

In the end I decided to go with a more portable solution, embedding the fasttext binary compiled into wasm:
https://github.com/loretoparisi/fasttext.js/tree/master/wasm
